name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          locked: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: pixi run pre-commit run --all-files
        env:
          SKIP: no-commit-to-branch

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          locked: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: pixi run pytest

  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          locked: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: python -m compileall src tests
